#Tested on icesugar revision 1.5
#This board does unfortunately not wire RTS/CTS through the stm32.
#Therefore, no hardware flow control.
programmer = icesprog
pcf = boards/icesugar/icesugar.pcf
chip = up5k
package = sg48
MHz = 12
dbusMHz = 6
uartrxbufpow2 = 13
uarttxbufpow2 = 12
uartrate = 57600
invleds = y
